### ISSUE TITLE
inline-стили не лучшее решение

### ISSUE THREAD

**Issue by coursar** [aygulmardanova/purchases-list#1]
https://github.com/aygulmardanova/purchases-list/blob/05bfce3076412f222daa76d688bd5b9130c26e25/src/index.html#L59

**Comment by aygulmardanova** [comment]
Нужно вынести в css-файл?

**Comment by aygulmardanova** [comment]
А где ширина задается через style="width:..%" тоже выносить? их ведь много, и они разные..

**Comment by coursar** [comment]
Для этого есть бутстрап ))
